version: '3.8'

services:
  conference-room-booking:
    container_name: conference-room-booking
    build:
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    networks:
      - app-network
    env_file:
      - .env

  mongo:
    image: mongo:5.0
    container_name: conference-room-booking-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=conference-room-bookings
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - ./database/db:/data/db
      - ./database/dev.archive:/Databases/dev.archive
      - ./database/production:/Databases/production

  mongo-express:
    image: mongo-express
    container_name: conference-room-booking-mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    ports:
      - '8081:8081'

networks:
  app-network:

volumes:
  mongodb-data:
